# Generated by Django 4.1 on 2022-08-24 08:24

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoint_date', models.DateTimeField(default='', max_length=builtins.max)),
                ('description', models.CharField(default='', max_length=200)),
                ('appoint_status', models.BooleanField(default=False)),
            ],
        ),
    ]
